#!/bin/bash
set -e
cd "$(realpath "$(dirname "$BASH_SOURCE")")/.."

qr=test/qr.png
qr_app_package=com.example.barcodescanner
qr_app_apk=test/$qr_app_package.apk

# Repeatedly try to execute a command
# usage: try COMMAND [COMMAND PARAMS ...]
try () {
    [[ -n "$1" ]] || {
        echo try function: bad usage >&2
        return 1
    }
    echo trying \`$*\` >&2
    tries=1
    until "$@" &> /dev/null; do
        let tries++
        echo tries: $tries $(tput cuu1) >&2
        sleep 1
    done
}

[[ -n "$ANDROID_HOME" ]] ||
    export ANDROID_HOME="$HOME/Android/Sdk"
which adb &> /dev/null ||
    export PATH="$ANDROID_HOME/platform-tools:$PATH"

which adb &> /dev/null || {
    cat >&2 <<- EOF
	Android SDK not found
	It is expected to be in \$ANDROID_HOME: ${ANDROID_HOME/$HOME/\~}
	EOF
    read -p 'Do you want to install it? (Y/n) ' answer >&2
    if [[ "$answer" != [Nn] ]]; then
        setup/android-sdk
    else
        exit 1
    fi
}

# Automatically kill ffmpeg and the emulator on exit
trap 'kill $ffmpeg_pid $emulator_pid &> /dev/null' EXIT INT TERM

# Start video stream
device=$(bin/stream "$qr")
ffmpeg_pid=$(cat /tmp/stream.pid)

# Wait for ffmpeg to start the stream
sleep 1

# Start emulator
bin/launch-emulator $device
emulator_pid=$(cat /tmp/emulator.pid)

# Download the QR scanner app
[[ -f "$qr_app_apk" ]] ||
    curl -Lo "$qr_app_apk" \
    'https://github.com/albertolazari/qr-barcode-scanner/releases/download/v1.0/com.example.barcodescanner.apk'

echo Waiting for the emulator to start
adb wait-for-device

# Install the app
if try adb shell pm list packages | grep -q $qr_app_package; then
    try adb uninstall $qr_app_package
fi
try adb install "$qr_app_apk"
# Automatically grant permission
try adb shell pm grant $qr_app_package android.permission.CAMERA
# Launch the app
try adb shell "am start -n $qr_app_package/$qr_app_package.feature.tabs.BottomTabsActivity && \
    dumpsys activity activities | grep mFocusedWindow.*$qr_app_package"
echo Scanning the QR

adb logcat -c
# Get the scanned value
qr_value=$(grep -m 1 QRSCAN < <(adb logcat -s QRSCAN) |
    sed 's/^.*QRSCAN *: *\(.*\)$/\1/')
echo Scanned value: $qr_value
