#!/bin/bash
set -e

if [[ -n "$1" ]]; then
    video="$1"
else
    echo usage: change-video VIDEO >&2
    exit 1
fi

device="/dev/$(ls /sys/devices/virtual/video4linux 2> /dev/null | head -1)"
if ! grep -q '^/dev/video[0-9]*$' <<< "$device"; then
    echo Virtual webcam not found >&2
    exit 1
fi

killall ffmpeg
&> /tmp/ffmpeg.log ffmpeg -stream_loop -1 -re -i "$1" -f v4l2 $device &
