#!/bin/bash
set -e
cd "$(dirname "$BASH_SOURCE")"

log () {
    echo "[[1;34m$0[0m] $@"
}

ok () {
    echo "[[1;32mOK[0m] $@"
}

# Set Android SDK variables
[[ -n "$ANDROID_HOME" ]] ||
    export ANDROID_HOME="$HOME/Android/Sdk"
which sdkmanager &> /dev/null ||
    export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"

# The setup will be triggered when either the SDK or the virtual device are not present
if ! avdmanager list avd 2> /dev/null | grep -q qrfuzz; then
    log Installing Android SDK in $ANDROID_HOME
    setup/android-sdk
else
    ok Android SDK already installed
fi

if ! lsmod | grep -q v4l2loopback; then
    log 'Installing `v4l2loopback` kernel module'
    setup/v4l2loopback
else
    ok '`v4l2loopback` kernel module already loaded'
fi

if ! which ffmpeg &> /dev/null; then
    log Installing FFmpeg
    setup/ffmpeg
else
    ok ffmpeg already installed
fi

[[ -n "$NVM_DIR" ]] || export NVM_DIR="$HOME/.nvm"
[[ -s "$NVM_DIR/nvm.sh" ]] && . "$NVM_DIR/nvm.sh"

if ! which npm &> /dev/null; then
    log Installing Node.js
    setup/nodejs
else
    ok Node.js already installed
fi

# The setup will be triggered when either the driver or appium itself are missing
if ! appium driver list --installed 2>&1 | grep -q uiautomator2; then
    log Installing Appium
    setup/appium
else
    ok Appium already installed
fi

if npm list 2> /dev/null | grep -q 'UNMET DEPENDENCY'; then
    log Installing fuzzer
    setup/fuzzer
else
    ok Fuzzer already installed
fi
