#!/bin/bash
set -e
cd "$(dirname "$BASH_SOURCE")"

. lib/log.sh
. lib/dependency.sh

if check android_sdk avd; then
    ok Android SDK already installed
else
    log Installing Android SDK in $ANDROID_HOME
    setup/android-sdk
fi

if check v4l2loopback; then
    ok '`v4l2loopback` kernel module already loaded'
else
    log 'Installing `v4l2loopback` kernel module'
    setup/v4l2loopback
fi

if check ffmpeg; then
    ok ffmpeg already installed
else
    log Installing FFmpeg
    setup/ffmpeg
fi

if check nodejs; then
    ok Node.js already installed
else
    log Installing Node.js
    setup/nodejs
fi

# The setup will be triggered when either the driver or appium itself are missing
if check appium; then
    ok Appium already installed
else
    log Installing Appium
    setup/appium
fi

if check fuzzer; then
    ok Fuzzer already installed
else
    log Installing fuzzer
    setup/fuzzer
fi
