#!/bin/bash
set -e
cd "$(realpath "$(dirname "$BASH_SOURCE")")/.."

. lib/log.sh
. lib/dependencies.sh

require android_sdk avd

pid_file=/tmp/emulator.pid

print_usage () {
    cat >&2 <<- EOF
	usage: launch-emulator [<webcam_device>] [<emulator_args> ...]
	Launch an emulator instance
	- Returns the emulator PID in \`/tmp/emulator.pid\`

	arguments:
	  <webcam_device>   path of the \`/dev/videoN\` device to use as webcam (optional)
	  <emulator_args>   additional arguments to pass to the emulator (optional)
	options:
	  -h, --help        show this message
	EOF
}

case "$1" in
    -h | --help)
        print_usage
        exit
        ;;
    # Do nothing, no device was passed, only emulator options
    -*) ;;
    *)  device="$1"
        shift
        ;;
esac

emulator_args=(
    @qrfuzz
    "$@"
)

if [[ -f "$pid_file" ]] && ps -p $(cat "$pid_file") &> /dev/null; then
    warning An emulator instance is already running
    exit 0
fi

[[ -z "$device" ]] || {
    # Get webcam name from emulator
    webcam=$(emulator -webcam-list 2> /dev/null | grep "$device" | grep -o 'webcam[0-9]*') ||
        error Android emulator could not find a webcam on \`$device\`
    emulator_args+=(-camera-back "$webcam")
}

# Launch the emulator
emulator &> /tmp/emulator.log \
    "${emulator_args[@]}" \
    &

# Save the emulator PID
echo $! > "$pid_file"
