#!/bin/bash
set -e
cd "$(realpath "$(dirname "$BASH_SOURCE")")/.."

pid_file=/tmp/emulator.pid

log () {
    echo "[[1;34m$0[0m] $@"
}
warning () {
    log "[[1;33mWARNING[0m] $@" >&2
}
error () {
    log "[[1;31mERROR[0m] $@" >&2
    exit 1
}

print_usage () {
    cat >&2 <<- EOF
	usage: launch-emulator [WEBCAM_DEVICE] [EMULATOR_ARGS ...]
	Launch an emulator instance
	- Returns the emulator PID in \`/tmp/emulator.pid\`

	arguments:
      WEBCAM_DEVICE     path of the \`/dev/videoN\` device to use as webcam (optional)
      EMULATOR_ARGS     additional arguments to pass to the emulator (optional)
	options:
	  -h, --help        show this message
	EOF
}

case "$1" in
    -h | --help)
        print_usage
        exit
        ;;
    *)  device="$1"
        # Device may not be provided
        [[ -z "$device" ]] ||
            shift
        ;;
esac

emulator_args=(
    @qrfuzz
    "$@"
)

if [[ -f "$pid_file" ]] && ps -p $(cat "$pid_file") &> /dev/null; then
    warning An emulator instance is already running
    exit 0
fi

[[ -n "$ANDROID_HOME" ]] ||
    export ANDROID_HOME="$HOME/Android/Sdk"
which emulator &> /dev/null ||
    export PATH="$ANDROID_HOME/emulator:$PATH"

which emulator &> /dev/null || {
    cat >&2 <<- EOF
	Android SDK not found
	It is expected to be in \$ANDROID_HOME: ${ANDROID_HOME/$HOME/\~}
	EOF
    read -p 'Do you want to install it? (Y/n) ' answer >&2
    if [[ "$answer" != [Nn] ]]; then
        setup/android-sdk
    else
        exit 1
    fi
}

[[ -z "$device" ]] || {
    # Get webcam name from emulator
    webcam=$(emulator -webcam-list 2> /dev/null | grep "$device" | grep -o 'webcam[0-9]*') ||
        error Android emulator could not find a webcam on \`$device\`
    emulator_args+=(-camera-back "$webcam")
}

# Launch the emulator
emulator &> /tmp/emulator.log \
    "${emulator_args[@]}" \
    &

# Save the emulator PID
echo $! > "$pid_file"
