#!/bin/bash
set -e

if [[ $(uname) = Linux ]]; then
    os=linux
    export ANDROID_HOME=~/Android/Sdk
else
    echo OS not supported >&2
    exit 1
fi

if uname -m | grep -Eq '^(arm|aarch)64$'; then
    arch=arm64-v8a
else
    arch=x86_64
fi
system_image="system-images;android-34;google_apis_playstore;$arch"
device=qrfuzz

# Get from curl
if [[ ! -d "$ANDROID_HOME/cmdline-tools" ]]; then
    link="https://dl.google.com/android/repository/commandlinetools-$os-10406996_latest.zip"
    out=/tmp/commandlinetools-$os-10406996_latest.zip
    echo "Downloading Android SDK from $link"
    [[ -f "$out" ]] || curl -Lo "$out" "$link"

    echo Extracting downloaded package...
    [[ -d "$ANDROID_HOME/cmdline-tools" ]] || mkdir -p "$ANDROID_HOME/cmdline-tools"
    unzip -q "$out" -d "$ANDROID_HOME/cmdline-tools" && rm "$out"

    mv "$ANDROID_HOME/cmdline-tools/cmdline-tools" "$ANDROID_HOME/cmdline-tools/latest"
fi

which sdkmanager &> /dev/null ||
    export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"

# Accept licenses
yes | sdkmanager --install \
    'platform-tools' \
    'platforms;android-34' \
    'build-tools;34.0.0' \
    "$system_image"

echo Creating virtual device \`$device\`
echo no | avdmanager create avd > /dev/null \
    --force \
    -n $device \
    -k $system_image

# Enable buttons
sed -i'' 's/^hw\.keyboard=no/hw.keyboard=yes/' ~/.android/avd/$device.avd/config.ini
