#!/bin/bash
set -e
cd "$(realpath "$(dirname "$BASH_SOURCE")")/.."

apk_directory=test/apks

log () {
    echo "[[1;34m$0[0m] $@"
}
warning () {
    log "[[1;33mWARNING[0m] $@" >&2
}
error () {
    log "[[1;31mERROR[0m] $@" >&2
    exit 1
}
ok () {
    log "[[1;32mOK[0m] $@"
}

print_help () {
    cat >&2 <<-EOF
	usage: apk [-h] APP [...]
	Download and install the required APP[s]

	arguments:
      APP [...]     the app (or multiple apps) to install
	options:
	  -h, --help    show this message
	EOF
}

[[ -n "$1" ]] || {
    print_help
    exit 1
}

case "$1" in
    -h | --help)
        print_help
        exit 0
        ;;
    *)  apps="$@" ;;
esac

# Check that the Android SDK is installed
[[ -n "$ANDROID_HOME" ]] ||
    export ANDROID_HOME="$HOME/Android/Sdk"
which adb &> /dev/null ||
    export PATH="$ANDROID_HOME/platform-tools:$PATH"
which adb &> /dev/null || {
    cat >&2 <<- EOF
	Android SDK not found
	It is expected to be in \$ANDROID_HOME: ${ANDROID_HOME/$HOME/\~}
	EOF
    read -p 'Do you want to install it? (Y/n) ' answer >&2
    if [[ "$answer" != [Nn] ]]; then
        setup/android-sdk
    else
        exit 1
    fi
}

# Start the emulator
log Starting Android emulator
# TODO: put a real camera
bin/launch-emulator /dev/video0

# Wait for the emulator to be ready
adb wait-for-device
until adb shell pm list packages &> /dev/null; do
    sleep 1
done

[[ -d "$apk_directory" ]] ||
    mkdir -p "$apk_directory"

for app in $apps; do
    download=true
    app_name=$(sed 's/.*/\u&/' <<< $app)
    file="$apk_directory/$app.apk"

    case $app in
        discord)
            package=com.discord
            link='https://dw29.uptodown.com/dwn/4v1DOXXxUtLz5E0FU9H39urRNzcdTplHuhm-C8NGsH4Xmg_imYVkY9SQdUPTLs9avOGP35RQWPTU-1vU8h8TKRSjeN-XHNX1apL0V6muTZ2zR55C5sz_Cee4ga9lRRHn/Cd9W8C_boVFnOF_VGIF2RgCS4JPqJrcCjALkN0Gy1dv71Dadvu1D-EMfV8DMZ8fx0xdoH4xlO0E_uugolv8dNtMNbEoE_lT3tA5phItm_JiU6szGb9x0e2S7EL7U73Ek/n8grr4pyo_-x1zTyLtGDqji6HiLQj00vgA4qorapm91Jer9fVbpp77WK_5V5yaxtDP8JJ-3fcdXb6NmXPfqyxp6wlQI7mpaMJ3KOkjZCcro=/discord-126-17-stable.apk'
            ;;
        postepay)
            package=posteitaliane.posteapp.apppostepay
            link='https://downloadr2.apkmirror.com/wp-content/uploads/2024/02/50/65c1eaf794a33/com.posteitaliane.spim_5.3.503-500003503_minAPI24(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk?verify=1707260619-6resV-5r1fCW6gMZQn6SVYj3vUUQwWvNOz8F62_RSQI'
            ;;
        *)  warning \`$app_name\` is not configured yet
            # Skip installation
            continue
            ;;
    esac

    ! adb shell pm list packages | grep -q $package || {
        ok $app_name is already installed
        continue
    }

    # Check if file is already downloaded
    [[ ! -f "$file" ]] || {
        ok $app_name already downloaded in $file
        download=false
    }

    ! $download || {
        log Downloading $app_name
        curl -L "$link" -o "$file"
        ok $app_name downloaded in $file
    }

    log Installing $app_name
    until adb install "$file" &> /dev/null; do
        sleep 1
    done
    ok $app_name installed
done
