#!/bin/bash
set -e

# NVM might need its environment
[[ -n "$NVM_DIR" ]] || export NVM_DIR="$HOME/.nvm"
[[ -s "$NVM_DIR/nvm.sh" ]] && . "$NVM_DIR/nvm.sh"

which npm &> /dev/null || {
    echo $0: installing dependency: Node.js
    setup/nodejs
}

which appium &> /dev/null || {
    echo $0: installing Appium from npm
    npm install -g appium ||
        # Might need root access
        sudo npm install -g appium
}

appium driver list --installed 2>&1 | grep -q uiautomator2 || {
    echo $0: installing \`uiautomator2\` driver
    appium driver install uiautomator2
}
