#!/bin/bash
set -e

which npm &> /dev/null || {
    echo $0: installing dependency: Node.js
    setup/nodejs
}

which appium &> /dev/null || {
    echo $0: installing Appium from npm
    sudo npm install -g appium
}

appium driver list --installed 2>&1 | grep -q uiautomator2 || {
    echo $0: installing \`uiautomator2\` driver
    appium driver install uiautomator2
}
