#!/bin/bash
set -e
cd "$(realpath "$(dirname "$BASH_SOURCE")")/.."

. lib/log.sh
. lib/dependency.sh

require nodejs

check appium || {
    log Installing Appium
    npm install -g appium ||
        # Might need root access
        sudo npm install -g appium
}

check appium || {
    log Installing \`uiautomator2\` driver
    appium driver install uiautomator2
}
