#!/bin/bash
set -e

log () {
    echo "[[1;34m$0[0m] $@"
}

error () {
    log "[[1;31mERROR[0m] $@" >&2
    exit 1
}

# Debian-based
if which apt &> /dev/null; then
    log 'Running: sudo apt update && sudo apt install ffmpeg'
    sudo apt update
    sudo apt install ffmpeg
# Arch-based
elif which pacman &> /dev/null; then
    log 'Running: sudo pacman -S ffmpeg'
    sudo pacman -S ffmpeg
# RHEL-based
elif which dnf &> /dev/null; then
    log 'Running: sudo dnf install ffmpeg'
    sudo dnf install ffmpeg
else
    error No supported package manager was found
fi
