#!/bin/bash
set -e

# Debian-based
if which apt &> /dev/null; then
    sudo apt install ffmpeg -y ;;
# Arch-based
elif which pacman &> /dev/null; then
    sudo pacman -S ffmpeg --noconfirm ;;
# RHEL-based
elif which dnf &> /dev/null; then
    sudo dnf install --assumeyes ffmpeg ;;
fi
