#!/bin/bash
set -e
cd "$(realpath "$(dirname "$BASH_SOURCE")")/.."

log () {
    echo "[[1;34m$0[0m] $@"
}

# NVM might need its environment
[[ -n "$NVM_DIR" ]] || export NVM_DIR="$HOME/.nvm"
[[ -s "$NVM_DIR/nvm.sh" ]] && . "$NVM_DIR/nvm.sh"

which appium &> /dev/null || {
    log Installing dependency: Appium
    setup/appium
}

which tsc &> /dev/null || {
    log Installing dependency: TypeScript
    npm install -g typescript
}

! npm list 2> /dev/null | grep -q 'UNMET DEPENDENCY' || {
    log Installing fuzzer
    npm install
}
