#!/bin/bash
set -e
cd "$(realpath "$(dirname "$BASH_SOURCE")")/.."

. lib/log.sh
. lib/dependencies.sh

require appium

which tsc &> /dev/null || {
    log Installing dependency: TypeScript
    npm install -g typescript ||
        # Might need root access
        sudo npm install -g typescript
}

check fuzzer || {
    log Installing fuzzer
    npm install
}
