#!/bin/bash
set -e

log () {
    echo "[[1;34m$0[0m] $@"
}

which nvm &> /dev/null || {
    log Installing NVM
    curl "https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh" |
        bash

    export NVM_DIR="$HOME/.nvm"
    [[ -s "$NVM_DIR/nvm.sh" ]] && . "$NVM_DIR/nvm.sh"
}

log Installing Node.js using NVM
nvm install --lts
