#!/bin/bash
set -e
cd "$(realpath "$(dirname "$BASH_SOURCE")")/.."

. lib/log.sh

which nvm &> /dev/null || {
    log Installing NVM
    curl "https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh" |
        bash

    export NVM_DIR="$HOME/.nvm"
    [[ -s "$NVM_DIR/nvm.sh" ]] && . "$NVM_DIR/nvm.sh"
}

log Installing Node.js using NVM
nvm install --lts
