#!/bin/bash
set -e

which nvm &> /dev/null || {
    echo $0: installing nvm
    curl "https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh" |
        bash

    export NVM_DIR="$HOME/.nvm"
    [[ -s "$NVM_DIR/nvm.sh" ]] && . "$NVM_DIR/nvm.sh"
}

nvm install --lts
