#!/bin/bash
set -e
cd "$(realpath "$(dirname "$BASH_SOURCE")")/.."

. lib/log.sh
. lib/dependencies.sh

check nvm || {
    log Installing NVM
    curl "https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh" |
        bash
}
