#!/bin/bash
set -e
cd "$(realpath "$(dirname "$BASH_SOURCE")")/.."

. lib/log.sh

log 'Loading `v4l2loopback` kernel module (requires password)'
# Just load it if already installed
! sudo modprobe v4l2loopback 2> /dev/null || exit 0

warning Module not found
read -p 'Do you want to install it? (Y/n) ' answer >&2
[[ "$answer" != [Nn] ]] ||
    exit 1

dir=/tmp/v4l2loopback-repo
[[ ! -d "$dir" ]] || rm -rf "$dir"

log Cloning repo
git clone -q https://github.com/umlaeute/v4l2loopback "$dir"

# Install
log Installing
(
    cd "$dir"
    make > /dev/null
    sudo make install &> /dev/null
    sudo depmod -a
)

# Load module
log 'Loading kernel module `v4l2loopback`'
sudo modprobe v4l2loopback

rm -rf "$dir"
